server:
  port: '8082'

spring:
  application.name: temperature-monitoring
  datasource:
    username: sa
    url: jdbc:h2:file:~/algasensors-temperature-monitoring-db;CASE_INSENSITIVE_IDENTIFIERS=TRUE;
    driverClassName: org.h2.Driver
    password: '123'
  h2:
    console:
      enabled: 'true'
      settings.web-allow-others: 'true'
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: 'true'
    properties:
      hibernate:
          format_sql: true
# Configurações de logging
logging:
  level:
    # Define o nível de log para o Hibernate SQL como DEBUG para mostrar as queries
    org.hibernate.SQL: DEBUG
    # Define o nível de log para os parâmetros de bind do JDBC como TRACE
    # Isso mostrará os valores que estão sendo passados para os '?' nas queries
    org.hibernate.orm.jdbc.bind: TRACE